import torch


params = {
    "data_dir": "../data/mimicsql_data/mimicsql_natural",
    "results_dir": "../results",
    "file_train": "train.json",
    "file_val": "dev.json",
    "file_test": "test.json",
    "n_epoch": 2,
    "batch_size": 16,
    "checkpoint": 100,
    "val_num_batch": 100,
    "nbestmodel": 5,
    "continue_decoding": False,
    "continue_training": True,
    "train_base_model": False,
    "use_move_avg": False,
    "use_optimal_model": True,
    "model_optimal_key": "0,0",
    "is_lower": True,
    "device": torch.device("cpu:0"),
    "file_vocab": "vocab",
    "max_vocab_size": 50000,
    "word_minfreq": 5,
    "emb_dim": 128,
    "src_hidden_dim": 256,
    "trg_hidden_dim": 256,
    "src_seq_len": 400,
    "trg_seq_len": 100,
    "nLayers": 1,
    "learning_rate": 0.0005,
    "grad_clip": 2.0,
    "file_output": "test-output.json",
    "beam_size": 5,
    "copy_words": True,
    "step_size": 2,
    "step_decay": 0.8,
}
